### ISSUE TITLE
Question Issue

### ISSUE THREAD

**Issue by yunsujeon** [JeongMyeong/lotte-visionAI-competition#1]
제가 이해를 잘 못한건지 모르겠는데.. 질문이 있습니다.

baseline code 에서 75~79점이 나오셨고 이걸 극복하고자 augmentation 을 시도하셨다고 하셨는데요 

Experiments Results 에서 None 일때의 score가 91.458점 이시더라구요..

75~79점과 91.457점간에는 어떤 작업을 해주신건가요?

**Comment by JeongMyeong** [comment]
안녕하세요.
제가 작성한 solution에 관심을 가지고 질문 주셔서 감사합니다.
답변드립니다.

baseline code로 둔 EfficientNet 모델이 75~79점 정도 기록했습니다.

그리고 좀 더 좋은 성능을 바라고 augmentation을 시도하였습니다.

Experiments Results의 첫 번째 표는 augmentation 방법들을 하나씩 제외 했을 때 성능을 기록한 것입니다.

그래서 None이라는 것은 제가 설정했던 모든 augmentation 방법들을 모두 적용한 상태입니다. 그래서 ```91.457``` 점수가 나왔습니다.

결국 75~79점 과 91.457 점 사이에 했던 작업은 모든 augmentation 방법을 적용시킨 것입니다.

첫 번 째 표에서 augmentation 방법들을 하나씩 제거 해보면서 실험한 이유는 각각의 augmentation 방법이 데이터와 모델에 잘 적용 되어 좋은 성능을 보이는지 확인하기 위해 실험한 것입니다.

제 답변이 도움이 되었으면 좋겠습니다.

추가로 제 solution에 궁금한 점이 있으면 또 남겨주세요. 

감사합니다!

**Comment by yunsujeon** [comment]
아 제외 aug 가 None 이라는 말씀이셨군요

잘못 이해했습니다.. ㅎㅎ

답변감사합니다!
